### ISSUE TITLE
[Chapter 05] 151-152 페이지 saveAll 테스트 질문

### ISSUE THREAD

**Issue by yanJuicy** [shinsunyoung/springboot-developer-2rd#1]
아래 코드와 같이 Member 객체를 생성할 때 id 값이 2L, 1L 순서로 생성하고 saveAll을 시도하면 에러가 발생합니다.
```java
@Test
void saveMembers() {
    List<Member> members = List.of(new Member(2L, "B"), new Member(1L, "C"));

    memberRepository.saveAll(members);

    assertThat(memberRepository.findAll().size()).isEqualTo(2);
}
```

<img width="1508" alt="image" src="https://github.com/shinsunyoung/springboot-developer-2rd/assets/43159295/496910eb-c18b-4384-8ea4-72001579c399">

id 값 순서를 바꿔 1L, 2L 순서로 saveAll을 시도하면 정상적으로 되는데 이유가 뭔가요?
<img width="1552" alt="image" src="https://github.com/shinsunyoung/springboot-developer-2rd/assets/43159295/22ebe730-544a-4426-9a7e-548127fe690e">

추가적으로 여러 시도를 해보니 맨 뒤 Member의 id가 1L일 때만 이 현상이 나왔습니다. 0L, -1L로 바꿔도 정상 작동했습니다.

**Comment by chanseob** [comment]
저는 다른 프로그래밍 언어와 DB를 주로 사용하다 이번에 스프링부트를 공부중인데.
이슈로 남기신 내용은 아마도 DB에서는 순차적으로 1행, 2행 이렇게 저장이 되어야 하는데 2행(2L)부터 저장을 하면 ID값이 증가하는 방향으로만 생성되기 때문에 다음에 3행(3L)이 아닌 1행(1L)을 생성하려고 했을떄 에러가 나는것 같습니다.
에러 결과도 보면 완전한 에러라기 보다는 기대한 2행이 아닌 1행이라고 테스트가 실패한것으로 나옵니다.
아마도 2L만 제대로 저장이 되고 1L이 저장이 안되서 기대하기는 전체행수가 2행인데 실제 1행만 있어서 테스트가 실패한것 같습니다.

그래서 말씀하신것처럼 1L, 2L순으로 코드를 수정하면 정상적으로 테스트가 성공합니다.

**Comment by shinsunyoung** [comment]
안녕하세요! 말씀해주신 대로 id 값이 2L, 1L 순서로 생성하고 saveAll을 시도하면 아래와 같이 동작합니다.

1. new Member(2L, "B") 저장 -> id: 2가 있는지 검색 -> 없으니 insert -> `@GeneratedValue(strategy = GenerationType.IDENTITY)`이 걸려 있기 때문에 id: 1, name: "B"로 저장됨
2. new Member(1L, "C") 저장 -> id: 1이 있는지 검색 -> 이미 id: 1에는 "B"가 있음 -> name을 "C"로 업데이트

그래서 실제로 실행되는 쿼리문을 보면 insert, update문이 순서대로 실행되는 것을 확인하실 수 있습니다.
![image](https://github.com/shinsunyoung/springboot-developer-2rd/assets/42836576/9a4e2d60-0d79-478d-b429-b5e3571c4870)

제가 책에 부연 설명을 써놨어야 했는데 작성해두지 않아 혼란을 드린 것 같아 죄송합니다. 혹시나 이해가 되지 않는 부분이 더 있으면 알려주세요! 감사합니다. 🙇‍♀️

**Comment by yanJuicy** [comment]
@shinsunyoung  감사합니다!
