### ISSUE TITLE
[Chapter 03] @Autowired  Field injection is not recommended 

### ISSUE THREAD

**Issue by junhyunpark0716** [shinsunyoung/springboot-developer-2rd#10]
`@Autowired` 어노테이션을 사용하면 `Field injection is not recommended ` 메시지가 나오고, `create constructor` 메뉴가 생깁니다.

결국
```
    final
    TestService testService;

    public TestController(TestService testService) {
        this.testService = testService;
    }
```

이런식으로 바뀌게 되는데, 괜찮은건가요?? constructor 역할이 정확이 뭔지 모르겠습니다.

**Comment by shinsunyoung** [comment]
안녕하세요, `@Autowired`를 사용하는 것은 필드 주입 방식을 사용하는 것이고, 변경하신 방법은 생성자 주입 방식을 사용하는 것인데요. 필드 주입 방식에는 몇 가지 잠재적인 문제가 있기 때문에 조금 더 안전하게 사용하는 것(생성자 주입 방식)을 권장하고자 Warning 메세지가 나온 것입니다. 필드 주입 방식, 생성자 주입 방식 둘 중 어느 것을 사용해도 상관은 없습니다.

필드 주입 방식, 생성자 주입 방식 차이: https://mangkyu.tistory.com/125
Field injection is not recommended  메시지가 나오는 이유: https://www.baeldung.com/java-spring-field-injection-cons

**Comment by shinsunyoung** [comment]
해당 이슈 오랫동안 업데이트가 없어 닫아두겠습니다. 추가 질문 사항 생기면 reopen 부탁드립니다. 감사합니다!
