### ISSUE TITLE
[Ch06 / p.152, 154, 159 / BlogApiController] @PathVariable -> @PathVariable("id") 변경 고려 요청

### ISSUE THREAD

**Issue by hyojukim-game-on** [shinsunyoung/springboot-developer-2rd#15]
선영 저자님 안녕하세요 :) 
코드가 깔끔하고 가독성이 좋아서 많이 배우고 있습니다.

제가 실습했던 환경에서는 parameter 를 명시해주지 않았을 때, Exception 이 발생해서 리뷰 남깁니다.
찾아보니 명시하지 않아도 작동한다고 되어 있던데, 제 환경에서는 안 되더라구요.
변경하지 않으시더라도 알고 계시면 좋을 것 같아서 이슈 남깁니다 !

6.5 블로그 글 조회 API 구현하기 > 6.5.2 컨트롤러 메서드 코드 작성하기

**기존 코드**
```java
public ResponseEntity<ArticleResponse> findArticle(@PathVariable long id) {
}
```

**제안드리는 코드**
```java
public ResponseEntity<ArticleResponse> findArticle(@PathVariable("id") long id) {
}
```

**Comment by shinsunyoung** [comment]
안녕하세요! 좋은 개선 의견 감사합니다.
해당 부분 담당자님께 전달드려 반영할 수 있도록 하겠습니다 🙇

**Comment by myeongseung** [comment]
저도 같은 방법으로 해결하였습니다. 감사합니다

**Comment by justintime1118** [comment]
저도 같은 증상이 발생해서 와봤더니 역시 이미 다른 분이 올려주신 이슈가 있네요.
예전에 비슷한 문제로 고통받은 적이 있어 당시 참고했던 [링크](https://www.inflearn.com/community/questions/1087879/pathvariable-name-%EC%83%9D%EB%9E%B5-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4) 공유합니다 :)
