### ISSUE TITLE
[Ch07/p.186] @RequestParam(required = false) Long id -> @RequestParam(value="id", required = false) Long id 변경 고려 요청 

### ISSUE THREAD

**Issue by hyojukim-game-on** [shinsunyoung/springboot-developer-2rd#16]
선영 저자님 , 늘 감사합니다 :)

명시적으로 id parameter 를 작성하는 것보다 혹시 작성하지 않는 편이 유지 보수에 나은지 궁금합니다 ! 

**기존 코드**
```java
@GetMapping("/new-article")
public String newArticle(@RequestParam(required = false) Long id, Model model) {
}
```

**생각해본 코드**
```java
@GetMapping("/new-article")
public String newArticle(@RequestParam(value = "id", required = false) Long id, Model model) {
}
```

**Comment by shinsunyoung** [comment]
안녕하세요, 저는 value 값 까지 쓰는게 verbose 하다고 생각하기 때문에 생략하여 쓰는 편이지만 개인적인 스타일 차이에 따라 명시적으로 value 값을 작성해도 문제 없습니다. 
"명시적으로 id parameter 를 작성하는 것"에 따라 유지 보수성이 많이 갈리지 않는다고 생각합니다. 다만 두 스타일 모두 각각의 장단점이 있기 때문에 더 좋다고 생각하시는 방향대로 쓰시는 것을 추천드려요 🙇

**Comment by hyojukim-game-on** [comment]
답장해주셔서 감사합니다 !!
