### ISSUE TITLE
[Ch10] Spring Security의 Lambda DSL 사용 강제로 인한 WebOAuthSecurityConfig변경 요청

### ISSUE THREAD

**Issue by hyojukim-game-on** [shinsunyoung/springboot-developer-2rd#18]
[Spring Security 7 에서 반드시 Lambda DSL을 사용](https://docs.spring.io/spring-security/reference/migration-7/configuration.html#_goals_of_the_lambda_dsl)하도록 하고 있습니다.

아래는 Spring 에서 제시한 Lambda DSL 사용 목적입니다.
- 가독성: 코드 들여쓰기가 자동으로 적용되어 설정 코드를 읽기 쉽게 합니다.
- 연결 방식: .and() 메서드를 사용하여 설정을 연결할 필요가 없습니다.
- 일관성: Spring Integration 및 Spring Cloud Gateway와 같은 다른 Spring DSL과 유사한 설정 스타일을 제공합니다.

이에 따라 Spring Security 6.2.0 에서도 Lambda DSL 을 사용하지 않으면, 코드가 동작하지 않고 있습니다 !
![image](https://github.com/shinsunyoung/springboot-developer-2rd/assets/139435373/d3eb872d-5d3a-4741-8ce1-d82911fb7da9)

이에 따라,
초판 Ch10 > 10.3.4 OAuth2 설정 파일 작성하기 > 2단계 `/config/WebOAuthSecurityConfig.java` 수정 요청 드립니다.

Lambda DSL 을 적용해서 제가 수정해본 코드는 [여기](https://github.com/hyojukim-game-on/learn-spring-security/blob/master/tuser/src/main/java/com/toy/tuser/config/WebOAuthSecurityConfig.java) 있습니다.
이런 식으로 최종 수정하실 지는 모르겠지만, 참고가 되실 것 같아서 전달 드립니다 !

감사합니다 :)

**Comment by shinsunyoung** [comment]
안녕하세요, 많은 개선 의견 주셔서 진심으로 감사드립니다. 🙇 
공유해주신 소중한 의견들과 코드는 잘 갈음해서 다음 쇄에 반영하도록 하겠습니다. 
도움 주셔서 다시 한 번 감사합니다! 👍👍
