### ISSUE TITLE
[Chapter 6] dto에 대해서 질문있습니다.

### ISSUE THREAD

**Issue by seungwoo-project** [shinsunyoung/springboot-developer-2rd#21]
@RestController
    @RequiredArgsConstructor
    public class BlogController {

    private final BlogService blogService;

    // 글 생성
    @PostMapping("/api/articles")
    public ResponseEntity<Article> addArticle(@RequestBody AddArticleRequest request) {
        Article savedArticle = blogService.save(request);

        return ResponseEntity.status(HttpStatus.CREATED).body(savedArticle);
    }

    // 글 전체 조회
    @GetMapping("/api/articles")
    public ResponseEntity<List<ArticleResponse>> findAllArticles() {
        List<ArticleResponse> articles = blogService.findAll().stream().map(a -> new ArticleResponse(a)).toList();
        return ResponseEntity.ok().body(articles);
    }

    // 글 단일 조회
    @GetMapping("/api/articles/{id}")
    public ResponseEntity<ArticleResponse> findArticle(@PathVariable("id") Long id) {
        Article findArticle = blogService.findById(id);
        ArticleResponse articleResponse = new ArticleResponse(findArticle);
        return ResponseEntity.ok().body(articleResponse);
    }

    // 글 수정
    @PutMapping("/api/articles/{id}")
    public ResponseEntity<ArticleResponse> updateArticle(@PathVariable("id") Long id, @RequestBody UpdateArticleRequest request) {
        Article updateArticle = blogService.update(id, request);
        ArticleResponse articleResponse = new ArticleResponse(updateArticle);
        return ResponseEntity.status(HttpStatus.OK).body(articleResponse);
    }
    // 글 삭제
    @DeleteMapping("/api/articles/{id}")
    public ResponseEntity<Void> deleteArticle(@PathVariable("id") Long id) {
        blogService.deleteById(id);
        return ResponseEntity.ok().build();
    }
    }

글 생성이나 수정할때는 왜 따로 dto를 안만들고 entity를 리턴하나요? 궁금해서 질문남깁니다!

**Comment by shinsunyoung** [comment]
DTO를 만들어서 반환해도 상관 없습니다. 실제로 저도 개발할 땐 응답 객체로 DTO를 반환하도록 구현하는 편이지만, 책에서 모두 DTO로 반환하도록 구성하면 너무 많은 코드가 반복되기 때문에 엔티티를 직접 반환하게 구현해두었다고 생각해주시면 될 것 같습니다. 🙇

**Comment by seungwoo-project** [comment]
아 넵! 알려주셔서 감사합니다~
