### ISSUE TITLE
[Chapter 8] localhost:8080/articles를 입력하면 어떤 원리로 /login으로 가는것인가요?

### ISSUE THREAD

**Issue by redgreen7** [shinsunyoung/springboot-developer-2rd#22]
[Chapter 8] localhost:8080/articles를 입력하면 어떤 원리로 /login으로 리다이렉트가 되는 것인지 문의 드립니다.
WebSecurityConfig.java

**Comment by shinsunyoung** [comment]
config 파일에서 설정한 formLogin의 loginPage Path가 /login 이기 때문입니다.
/articles에 접근하면 스프링 시큐리티 필터를 거치며 접근이 허용된 사용자인지 검증하게 되는데, 로그인을 하지 않은 상태면 접근이 허용되지 않은 유저이며 인증이 필요하기 때문에 설정된 loginPage로 이동하게 됩니다.

**Comment by shinsunyoung** [comment]
해당 이슈 오랫동안 업데이트가 없어 닫아두겠습니다. 추가 질문 사항 생기면 reopen 부탁드립니다. 감사합니다!
