### ISSUE TITLE
[Chapter 7] 등록 수정시 createAt, updateAt 오류

### ISSUE THREAD

**Issue by seungwoo-project** [shinsunyoung/springboot-developer-2rd#23]
등록과 수정시에 createAt, updateAt이 null값으로 들어가게 됩니다.

**Comment by seungwoo-project** [comment]
해결했습니다. domain/Article 클래스에 @EntityListeners(AuditingEntityListener.class)가 교안에 안나와있네요

또한, 수정시간 표시도 article.html에 추가해주고, ArticleViewResponse dto에 updateAt을 추가하여 수정시간도 표시되게 해결했습니다.

**Comment by shinsunyoung** [comment]
감사합니다! @EntityListeners(AuditingEntityListener.class)는 2판으로 넘어오면서 추가했던 것 같은데 다시 확인해보고 빠져있다면 수정해서 반영할 수 있도록 하겠습니다 🙇
