### ISSUE TITLE
2판 개정에 대해 궁금한 것이 있습니다!!

### ISSUE THREAD

**Issue by GRAY-DDOT** [shinsunyoung/springboot-developer-2rd#28]
1판 공부중 개정판이 있다는 사실을 알아 개정판으로 다시 공부 중입니다.
1판 중간중간 취약점 발견 둥의 사유로 다음 버전부터 사용 불가능하거나 스프링 부트  최신 버전일 경우 이미 사용 불가능한 메소드들이 다수 있던 것으로 기억합니다.

궁금한 것은 다름이 아니라 개정 작업을 하실때 1판 코드를 2판으로 수정하신 과정이 궁금합니다. 정확히는 어떻게 확인하시고 최신 버전으로 변경하셨는지 궁금하다고 하는 것이 맞겠군요. 이 프로젝트를 발전시켜 하고 싶은 것이 다수 있는데, 이후 비슷한 취약점 보고 등으로 사용을 못하는 경우들에 어떻게 대응해야 할까요?

일일히 공식 문서를 확인하시면서 작업을 하신 것인지, 기존에 사용하시던 다른 방법을 사용을 하신것인지 작가님의 방법이 궁금하여 질문 남깁니다!

**Comment by shinsunyoung** [comment]
안녕하세요, 답변이 늦어 죄송합니다.
메이저한 버전 업데이트가 아니기 때문에 변경 사항이 많지 않았고, 최신버전으로 deprecated 된 코드(ex. Spring Security)에 대해서만 변경 작업을 했습니다. 작업할 때에는 공식문서를 참고했습니다.
더 궁금한점 있으면 추가 코멘트 남겨주세요. 감사합니다!
