### ISSUE TITLE
[Chapter 08] 스프링 시큐리티 + oauth

### ISSUE THREAD

**Issue by kodoyoon** [shinsunyoung/springboot-developer-2rd#3]
oauth 랑 스프링 시큐리티 동시에 작동하는 코드 좀 부탁드려도 괜찮을까요??ㅠㅠㅠㅠㅠㅠ

**Comment by shinsunyoung** [comment]
안녕하세요! 답변이 늦어 죄송합니다. OAuth가 스프링 시큐리티로 동작하는 것입니다. 혹시 다른 것을 말씀하시는걸까요?

**Comment by shinsunyoung** [comment]
오랫동안 추가 comment가 없어 요 이슈는 닫아두겠습니다. 추가적으로 질문이 생기시면 이슈를 다시 열어주시거나 새로운 이슈로 등록 부탁드립니다!
