### ISSUE TITLE
[Chapter 08] WebSecurityConfig 의 AuthenticationManager 부분에 UserDetailService userDetailService의 역할은 무엇인가요???

### ISSUE THREAD

**Issue by ironwhale1014** [shinsunyoung/springboot-developer-2rd#7]
안녕하세요 AuthenticationManager 만드는 부분에 파라메터로 UserDetailService userDetailService 들어갔는데 

실제로  authProvider.setUserDetailsService(userService);  
이부분에는 위에서 설정한 private final UserDetailService userService;  이게 들어가 

파라메터가 쓰이는 부분이 없어 필요가 없어 보이는데 용도가 무엇인가요??

`@Bean
    public AuthenticationManager authenticationManager(HttpSecurity http, BCryptPasswordEncoder bCryptPasswordEncoder, **UserDetailService userDetailService**) throws Exception {
        DaoAuthenticationProvider authProvider = new DaoAuthenticationProvider();
        authProvider.setUserDetailsService(**userService**);
        authProvider.setPasswordEncoder(bCryptPasswordEncoder);
        return new ProviderManager(authProvider);
    }`

**Comment by shinsunyoung** [comment]
안녕하세요, 저희가 UserDetailService라는 클래스를 만들었고, 거기에서 loadUserByUsername() 메서드를 재정의했는데요. 저희가 구현한 UserDetailService를 사용하도록 설정하는 것입니다.

https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/user-details-service.html

**Comment by ironwhale1014** [comment]
안녕하세요 
답변 감사합니다. 다만 제 질문의 의도는 
authenticationManager 메소드에 userDetailService 파라메터가 불필요한 파라메터로 보여 넣으신 이유가 먼지 궁금하다는 거였습니다. 
실제로는 파라메터로 들어온 userDetailService아닌 DI로 들어온 userService를 사용 하셨거든요

**Comment by ironwhale1014** [comment]
그리고 복습하다가 우연히 위에 질문 드린 AuthenticationManager를 빈에 등록하는 코드를 누락하고 진행했는데도 정상적으로 로그인이 동작하는데 세부적으로 커스텀하게 설정할지 않는다면 원래 없어도 동작하는 건가요??

`    @Bean
    public AuthenticationManager authenticationManager(HttpSecurity http, BCryptPasswordEncoder bCryptPasswordEncoder, UserDetailService userDetailService) throws Exception {
        DaoAuthenticationProvider authProvider = new DaoAuthenticationProvider();
        authProvider.setUserDetailsService(userService);
        authProvider.setPasswordEncoder(bCryptPasswordEncoder);
        return new ProviderManager(authProvider);
    }`

**Comment by shinsunyoung** [comment]
앗 답변이 늦어서 죄송합니다, 네 이해했습니다.

1. authenticationManager 메소드에 userDetailService 파라메터가 불필요한 파라메터로 보여 넣으신 이유가 먼지 궁금하다는 거였습니다.
말씀주신대로 불필요한 파라미터이고, 아래 코드처럼 http, userDetailService를 제거하고 사용하셔도 상관 없습니다. 제가 스프링 시큐리티 버전 업그레이션 가이드를 참고하며 요 코드를 작성했는데요. 그 과정에서 필요없는 파라미터가 들어간 것으로 보입니다. 요건 헷갈릴 여지가 있으니 다음 부를 찍을 때 수정 요청 해두도록 하겠습니다. 감사합니다!

```
    @Bean
    public AuthenticationManager authenticationManager(BCryptPasswordEncoder bCryptPasswordEncoder) {
        DaoAuthenticationProvider authProvider = new DaoAuthenticationProvider();
        authProvider.setUserDetailsService(userService);
        authProvider.setPasswordEncoder(bCryptPasswordEncoder);
        return new ProviderManager(authProvider);
    }
```


2. 그리고 복습하다가 우연히 위에 질문 드린 AuthenticationManager를 빈에 등록하는 코드를 누락하고 진행했는데도 정상적으로 로그인이 동작하는데 원래 없어도 동작하는 건가요??

기본적으로 스프링 시큐리티에서 제공해주는 설정이 있기 때문에 자동으로 UserDetailService를 감지하고 PassowordEncoder를 주입하여 보내줍니다. 별도로 작성한 이유는 구성과 추가적인 변경 사항이 생길 때 수정해야 하는 부분을 명시적으로 보여주기 위함이고, 말씀 주신 대로 작성하지 않아도 책에서 소개하고 있는 기능에 대해서는 잘 동작합니다.

추가적인 질문 있으시면 코멘트 달아주세요! 감사합니다.

**Comment by ironwhale1014** [comment]
의문이 잘 해결 되었습니다. 감사합니다.
